### PR TITLE
Feature: database connection and setup using diesel.rs orm

### LINKED ISSUE #4: Database setup
vps and database

### PR DESCRIPTION
**Pull request by NotSugat**
related to #4

### CODE REVIEW

**Comment by abhiyandhakal** [comment]
Awesome! It seems that the setup of diesel ORM only has been done. Will you also set up all the schemas?

**Comment by NotSugat** [comment]
> Awesome! It seems that the setup of diesel ORM only has been done. Will you also set up all the schemas?

okay I will work on it

**Comment by NotSugat** [comment]
database schema added

**Comment by abhiyandhakal** [comment]
@NotSugat please make the necessary changes and push, the PR has been open for too long.

**Comment by NotSugat** [comment]
Schema had been added to the pr

**Pull request merged**
