### PR TITLE
Feature 8 complete webview

### LINKED ISSUE #8: Complete webview
- Refresh
- Back
- Forward
- Back history
- Forward history
- Customize right click menu
- Permissions
- Inspect element
- Alert

### PR DESCRIPTION
**Pull request by kausik10**
Moved the reload, back and refresh button to the headerbar
Relates to #17

### CODE REVIEW

**Comment by abhiyandhakal** [comment]
Please add a comment in the description saying "relates to #17".

**Comment by abhiyandhakal** [comment]
I will review the code only after the master branch is pulled and merged into this branch. Please do so.

**Comment by abhiyandhakal** [comment]
I ran your code. Will you please change the reload button to `x` when the page is loading/reloading?

**Comment by kausik10** [comment]
Added Inspect on Right Click . Relates to #17

**Comment by NotSugat** [comment]
> Added Inspect on Right Click . Relates to #17

inspect not showing after right click

**Comment by abhiyandhakal** [comment]
I think you didn't git pull. Please make sure to do that

**Pull request merged**
